language: node_js
node_js:
  - "8"
  - "6"
dist: trusty # needs Ubuntu Trusty
sudo: required  # no need for virtualization.
addons:
  chrome: stable # have Travis install chrome stable.
after_script:
  - npm run coveralls
